apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kbot
  name: kbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kbot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: kbot
    spec:
      containers:
        - env:
            - name: METRICS_HOST
              value: collector:4317
            - name: TELE_TOKEN
              value: 6978966685:AAFgwhsw56AU2AGDBek74Exg0m94V4ANy60
          image: ghcr.io/sedrikkh/kbot.git:v1.0.7-3db997f-linux-amd64
          name: kbot
          resources: {}
      restartPolicy: Always
status: {}
